<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="EPINPUNW03CD" failures="1" tests="1" name="Default test" time="9.626" errors="0" timestamp="2023-04-05T00:58:38 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="9.08">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Resorce not deleted successfully expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Resorce not deleted successfully expected [404] but found [200]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at pages.HomeTaskRestFunctionalTest.verifyResourceIsDeleted(HomeTaskRestFunctionalTest.java:100)
at StepDefinitions.APITestingTask.verify_that_resource_has_been_deleted_succesfully(APITestingTask.java:57)
at âœ½.Verify that resource has been deleted succesfully(file:///C:/Users/Durgesh_Honrao/Desktop/Assignments/Epam/epam_onboarding_625745/src/test/java/feature/APITestingTask.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
